module.exports = [
  {
    fieldname: "image",
    originalname: "woody-kelly-8qLxn28Clko-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870177/UniCamping/jtdwd9plyqo7a5tbcj8f.jpg",
    size: 4918432,
    filename: "UniCamping/jtdwd9plyqo7a5tbcj8f",
  },
  {
    fieldname: "image",
    originalname: "aaron-weiss-yv6FRf8J5Sg-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870343/UniCamping/pkhzqvtkhhw24jk89kid.jpg",
    size: 2170059,
    filename: "UniCamping/pkhzqvtkhhw24jk89kid",
  },
  {
    fieldname: "image",
    originalname: "alexander-paul-jxd_BtnzQBQ-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870349/UniCamping/vmbwoheeevahevgljwuk.jpg",
    size: 2787229,
    filename: "UniCamping/vmbwoheeevahevgljwuk",
  },
  {
    fieldname: "image",
    originalname: "edho-fitrah-ELevCx8PX4o-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870356/UniCamping/lbzv8oxpenv5wc6rztdv.jpg",
    size: 3144225,
    filename: "UniCamping/lbzv8oxpenv5wc6rztdv",
  },
  {
    fieldname: "image",
    originalname: "federica-galli-pF1ug8ysTtY-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870371/UniCamping/ud0bezvompaiugx4pqw1.jpg",
    size: 6576050,
    filename: "UniCamping/ud0bezvompaiugx4pqw1",
  },
  {
    fieldname: "image",
    originalname: "igor-francetic-jJWtGV4QB4k-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870372/UniCamping/duzegdunnwyypghz22pb.jpg",
    size: 1030910,
    filename: "UniCamping/duzegdunnwyypghz22pb",
  },
  {
    fieldname: "image",
    originalname: "jeremy-bishop-dvACrXUExLs-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870376/UniCamping/g14jil9usu0mxf6bpcpb.jpg",
    size: 1923201,
    filename: "UniCamping/g14jil9usu0mxf6bpcpb",
  },
  {
    fieldname: "image",
    originalname: "jerry-zhang-Y8lCoTRgHPE-unsplash - Copia.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870383/UniCamping/seub0fsqxzyybchcq2o1.jpg",
    size: 3066965,
    filename: "UniCamping/seub0fsqxzyybchcq2o1",
  },
  {
    fieldname: "image",
    originalname: "joel-jasmin-forestbird-4S3iMBIappo-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870395/UniCamping/w2kuiznrsvc3wqhnujaf.jpg",
    size: 5710105,
    filename: "UniCamping/w2kuiznrsvc3wqhnujaf",
  },
  {
    fieldname: "image",
    originalname: "johannes-andersson-UCd78vfC8vU-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870406/UniCamping/tdzbhkikfhjcxeuibdft.jpg",
    size: 4488008,
    filename: "UniCamping/tdzbhkikfhjcxeuibdft",
  },
  {
    fieldname: "image",
    originalname: "josh-hild-8f_VQ3EFbTg-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870411/UniCamping/ivghiplxropybjkzsqob.jpg",
    size: 2642087,
    filename: "UniCamping/ivghiplxropybjkzsqob",
  },
  {
    fieldname: "image",
    originalname: "michael-loftus-DIQL8hKmVvw-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870417/UniCamping/xtmxj6s01alighhdbz2d.jpg",
    size: 2724431,
    filename: "UniCamping/xtmxj6s01alighhdbz2d",
  },
  {
    fieldname: "image",
    originalname: "olivier-miche-OZACaaUskhg-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870425/UniCamping/qpgeeaovajfxspozl8kh.jpg",
    size: 3625226,
    filename: "UniCamping/qpgeeaovajfxspozl8kh",
  },
  {
    fieldname: "image",
    originalname: "patrick-boucher-oHHph_yeMq8-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870430/UniCamping/uerziaio1dv4fwfl41wx.jpg",
    size: 2331965,
    filename: "UniCamping/uerziaio1dv4fwfl41wx",
  },
  {
    fieldname: "image",
    originalname: "paul-pastourmatzis-mqO0Rf-PUMs-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870431/UniCamping/speenhcis0xu0tammyfq.jpg",
    size: 565810,
    filename: "UniCamping/speenhcis0xu0tammyfq",
  },
  {
    fieldname: "image",
    originalname: "riccardo-chiarini-a4Swf9wzdKA-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870445/UniCamping/e23bvvnndlysqp4cyzfv.jpg",
    size: 6613013,
    filename: "UniCamping/e23bvvnndlysqp4cyzfv",
  },
  {
    fieldname: "image",
    originalname: "wei-zeng-mFohZ89GnZo-unsplash.jpg",
    encoding: "7bit",
    mimetype: "image/jpeg",
    path: "https://res.cloudinary.com/dimqowdvh/image/upload/v1689870455/UniCamping/ia6iafads9vlk3yifzek.jpg",
    size: 4622254,
    filename: "UniCamping/ia6iafads9vlk3yifzek",
  },
];
